service:
  type: NodePort
  nodePort: 32000

auth:
  enabled: true
  rootUser: admin
  rootPassword: password123

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 250m