namespace: aws-eshop

image:
  repository: "asingh1704/aws-eshop.client.app"
  tag: "{{ .Values.github.run_number }}"  # Helm cannot directly use environment variables like ${{ github.run_number }}; you need to pass this value during deployment.

deployment:
  name: aws-eshop-client-app
  replicas: 2

resources:
  limits:
    memory: 512Mi
    cpu: "1"
  requests:
    memory: 256Mi
    cpu: "0.2"

service:
  name: aws-eshop-client-app-service
  type: NodePort
  port: 80
  targetPort: 3000
  containerPort: 80
