apiVersion: v1
kind: Service
metadata:
  name: aws-eshop-client-app-service
spec:
  selector:
    app: aws-eshop-client-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort
