name: Build and Deploy React App on K8

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: # Allows manual triggering

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push microservice1
        run: |
          docker buildx build --tag asingh1704/aws-eshop.service.catalog:${{ github.run_number }} --push ./services/aws.eshop.catalog