name: Build and Deploy React App on K8

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push microservice1
        run: |
          docker buildx build --tag asingh1704/aws-eshop.client.app:${{ github.run_number }} --push ./clients/aws-eshop-app
  
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.2'  # Specify the version you need

      - name: Ensure .kube directory exists
        run: |
          mkdir -p $HOME/.kube
          
      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./infrastructure/k8s/aws-eshop-app/deployment.yaml
          kubectl apply -f ./infrastructure/k8s/aws-eshop-app/service.yaml
          kubectl rollout status deployment/aws-eshop-client-app